# Generated by Django 6.1 on 2026-08-14 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='gate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate', to='catalog.gates'),
        ),
    ]
